# Generated by Django 5.2 on 2025-04-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answered', models.IntegerField(default=1)),
                ('priority', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'EN'), ('RU', 'RU')], default='EN', max_length=5)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_language', models.CharField(choices=[('EN', 'EN'), ('RU', 'RU')], default='EN', max_length=5)),
                ('second_language', models.CharField(choices=[('EN', 'EN'), ('RU', 'RU')], default='RU', max_length=5)),
                ('cards', models.ManyToManyField(to='main.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translation'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('EN', 'EN'), ('RU', 'RU')], default='EN', max_length=5)),
                ('difficulty', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.word'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['-priority'], name='priority_desc_index'),
        ),
    ]
