# Generated by Django 5.2 on 2025-05-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='wrong_answered',
            field=models.IntegerField(default=0),
        ),
    ]
